### ISSUE TITLE
Hard coded values cause Juniper router to fail restore at TASK [network.restore.run : Copy file from src to a network device]

### ISSUE THREAD

**Issue by andubiel** [KB-perByte/network.restore#7]
##### SUMMARY

Hard Coded values cause problems with Juniper restore in
roles/run/includes/health_checks/junos.yaml 

Basically the following directory does not exist in the juniper router because the value in the collection is  based on the user home directory.

---
- name: Set JUNOS directory - content specific facts
  ansible.builtin.set_fact:
    dest_dir: "/var/home/ansible/"
    appliance_dir: "/var/home/ansible/"
    
    
 I recommend changing the directory something more generic that works on any juniper router:
 
 The following works:
 ---
- name: Set JUNOS directory - content specific facts
  ansible.builtin.set_fact:
    dest_dir: "/var/tmp/"
    appliance_dir: "/var/tmp/"
    
    Ididn't do the pull request in case you want to fix differently

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

network.restore

roles/run/includes/health_checks/junos.yaml 

##### ANSIBLE VERSION

```paste below
ansible-core                         2.15.6
```

##### COLLECTION VERSION

```paste below
network.backup            2.0.0  
network.base              5.0.0  
network.restore           1.0.0  
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

This is what it looks like after I correct the collection

```
TASK [network.restore.run : Copy file from src to a network device] ************
task path: /usr/share/ansible/collections/ansible_collections/network/restore/roles/run/includes/cli_restore.yaml:18
changed: [rtr3] => {
    "changed": true,
    "destination": "/var/tmp/20240430201245_junos_rtr3.txt"
}
```

##### ACTUAL RESULTS

```paste below
TASK [network.restore.run : Copy file from src to a network device] ************
changed: [rtr1]
fatal: [rtr3]: FAILED! => {"changed": true, "destination": "/var/home/ansible/20240430175055_junos_rtr3.txt", "msg": "Exception received: scp: /var/home/ansible/20240430175055_junos_rtr3.txt: No such file or directory\n"}
```

**Comment by rohitthakur2590** [comment]
@andubiel  Thank you, this looks good.
